package com.duke.orca.android.kotlin.biblelockscreen.persistence

object WordInjector {
    data class Word(
        val id: Int,
        val word: String
    )

    object AmericanKingJamesVersion {
        val words = arrayOf(
            Word(1532, "So Joseph died, being an hundred and ten years old: and they embalmed him, and he was put in a coffin in Egypt."),
            Word(2745, "For the cloud of the Lord was upon the tabernacle by day, and fire was on it by night, in the sight of all the house of Israel, throughout all their journeys."),
            Word(3604, "These are the commandments, which the Lord commanded Moses for the children of Israel in mount Sinai."),
            Word(4892, "These are the commandments and the judgments, which the Lord commanded by the hand of Moses unto the children of Israel in the plains of Moab by Jordan near Jericho."),
            Word(5851, "And in all that mighty hand, and in all the great terror which Moses shewed in the sight of all Israel."),
            Word(6509, "And Eleazar the son of Aaron died; and they buried him in a hill that pertained to Phinehas his son, which was given him in mount Ephraim."),
            Word(7127, "In those days there was no king in Israel: every man did that which was right in his own eyes."),
            Word(7212, "And Obed begat Jesse, and Jesse begat David."),
            Word(8022, "And they took their bones, and buried them under a tree at Jabesh, and fasted seven days."),
            Word(8717, "And David built there an altar unto the Lord, and offered burnt offerings and peace offerings. So the Lord was intreated for the land, and the plague was stayed from Israel."),
            Word(9533, "For he served Baal, and worshipped him, and provoked to anger the Lord God of Israel, according to all that his father had done."),
            Word(10252, "And his allowance was a continual allowance given him of the king, a daily rate for every day, all the days of his life."),
            Word(11194, "With all his reign and his might, and the times that went over him, and over Israel, and over all the kingdoms of the countries."),
            Word(12016, "Thus saith Cyrus king of Persia, All the kingdoms of the earth hath the Lord God of heaven given me; and he hath charged me to build him an house in Jerusalem, which is in Judah. Who is there among you of all his people? The Lord his God be with him, and let him go up."),
            Word(12296, "All these had taken strange wives: and some of them had wives by whom they had children."),
            Word(12702, "And for the wood offering, at times appointed, and for the firstfruits. Remember me, O my God, for good."),
            Word(12869, "For Mordecai the Jew was next unto king Ahasuerus, and great among the Jews, and accepted of the multitude of his brethren, seeking the wealth of his people, and speaking peace to all his seed."),
            Word(13939, "So Job died, being old and full of days."),
            Word(16400, "Let every thing that hath breath praise the Lord. Praise ye the Lord."),
            Word(17315, "Give her of the fruit of her hands and let her own works praise her in the gates."),
            Word(17537, "For God shall bring every work into judgment, with every secret thing, whether it be good, or whether it be evil."),
            Word(17654, "Make haste, my beloved, and be thou like to a roe or to a young hart upon the mountains of spices."),
            Word(18946, "And they shall go forth, and look upon the carcases of the men that have transgressed against me: for their worm shall not die, neither shall their fire be quenched; and they shall be an abhorring unto all flesh."),
            Word(20310, "And for his diet, there was a continual diet given him of the king of Babylon, every day a portion until the day of his death, all the days of his life."),
            Word(20464, "But thou hast utterly rejected us; thou art very wroth against us."),
            Word(21737, "It was round about eighteen thousand measures: and the name of the city from that day shall be, The Lord is there."),
            Word(22094, "But go thou thy way till the end be: for thou shalt rest, and stand in thy lot at the end of the days."),
            Word(22291, "Who is wise, and he shall understand these things? prudent, and he shall know them? for the ways of the Lord are right, and the just shall walk in them: but the transgressors shall fall therein."),
            Word(22364, "For I will cleanse their blood that I have not cleansed: for the Lord dwelleth in Zion."),
            Word(22510, "And I will plant them upon their land, and they shall no more be pulled up out of their land which I have given them, saith the Lord thy God."),
            Word(22531, "And saviours shall come up on mount Zion to judge the mount of Esau; and the kingdom shall be the Lord’s."),
            Word(22579, "And should not I spare Nineveh, that great city, wherein are more than sixscore thousand persons that cannot discern between their right hand and their left hand; and also much cattle?"),
            Word(22684, "Thou wilt perform the truth to Jacob, and the mercy to Abraham, which thou hast sworn unto our fathers from the days of old."),
            Word(22731, "There is no healing of thy bruise;thy wound is grievous:all that hear the bruit of thee shall clap the hands over thee:for upon whom hath not thy wickedness passed continually?"),
            Word(22787, "The Lord God is my strength, and he will make my feet like hinds’ feet, and he will make me to walk upon mine high places. To the chief singer on my stringed instruments."),
            Word(22840, "At that time will I bring you again, even in the time that I gather you:for I will make you a name and a praise among all people of the earth, when I turn back your captivity before your eyes, saith the Lord."),
            Word(22878, "In that day, saith the Lord of hosts, will I take thee, O Zerubbabel, my servant, the son of Shealtiel, saith the Lord, and will make thee as a signet: for I have chosen thee, saith the Lord of hosts."),
            Word(23089, "Yea, every pot in Jerusalem and in Judah shall be holiness unto the Lord of hosts: and all they that sacrifice shall come and take of them, and seethe therein: and in that day there shall be no more the Canaanite in the house of the Lord of hosts."),
            Word(23144, "And he shall turn the heart of the fathers to the children, and the heart of the children to their fathers, lest I come and smite the earth with a curse."),
            Word(24215, "Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you alway, even unto the end of the world. Amen."),
            Word(24893, "And they went forth, and preached every where, the Lord working with them, and confirming the word with signs following. Amen."),
            Word(26044, "And were continually in the temple, praising and blessing God. Amen."),
            Word(26923, "And there are also many other things which Jesus did, the which, if they should be written every one, I suppose that even the world itself could not contain the books that should be written. Amen."),
            Word(27930, "Preaching the kingdom of God, and teaching those things which concern the Lord Jesus Christ, with all confidence, no man forbidding him."),
            Word(28363, "To God only wise, be glory through Jesus Christ for ever. Amen."),
            Word(28800, "My love be with you all in Christ Jesus. Amen."),
            Word(29057, "The grace of the Lord Jesus Christ, and the love of God, and the communion of the Holy Ghost, be with you all. Amen."),
            Word(29206, "Brethren, the grace of our Lord Jesus Christ be with your spirit. Amen."),
            Word(29361, "Grace be with all them that love our Lord Jesus Christ in sincerity. Amen."),
            Word(29465, "The grace of our Lord Jesus Christ be with you all. Amen."),
            Word(29560, "The salutation by the hand of me Paul. Remember my bonds. Grace be with you. Amen."),
            Word(29649, "The grace of our Lord Jesus Christ be with you. Amen."),
            Word(29696, "The grace of our Lord Jesus Christ be with you all. Amen."),
            Word(29809, "Which some professing have erred concerning the faith. Grace be with thee. Amen."),
            Word(29892, "The Lord Jesus Christ be with thy spirit. Grace be with you. Amen."),
            Word(29938, "All that are with me salute thee. Greet them that love us in the faith. Grace be with you all. Amen."),
            Word(29963, "The grace of our Lord Jesus Christ be with your spirit. Amen."),
            Word(30266, "Grace be with you all. Amen."),
            Word(30374, "Let him know, that he which converteth the sinner from the error of his way shall save a soul from death, and shall hide a multitude of sins."),
            Word(30479, "Greet ye one another with a kiss of charity. Peace be with you all that are in Christ Jesus. Amen."),
            Word(30540, "But grow in grace, and in the knowledge of our Lord and Saviour Jesus Christ. To him be glory both now and for ever. Amen."),
            Word(30645, "Little children, keep yourselves from idols. Amen."),
            Word(30658, "The children of thy elect sister greet thee. Amen."),
            Word(30672, "But I trust I shall shortly see thee, and we shall speak face to face."),
            Word(30697, "To the only wise God our Saviour, be glory and majesty, dominion and power, both now and ever. Amen.")
        )
    }
}